### ISSUE TITLE
Get API Key

### ISSUE THREAD

**Issue by vitalii-honchar** [ParadexRelayer/Consumer-API-docs#8]
Hello!
I don't understand how I must receive API key?
Please, describe how receive API key...

Thanks,
Vitaliy

**Comment by donaldinho** [comment]
Hi Vitaliy
If you email contact@paradex.io we can get you set up
Cheers
Don

**Comment by vitalii-honchar** [comment]
I need exchange with API and test account. I found another exchange.

Thanks,
Vitaliy

**Comment by donaldinho** [comment]
Hi Vitaliy
We have a kovan version of our API which you can use to test. We issue both mainnet and kovan api keys to our users.
Cheers
Don
